### PR TITLE
Add Carthage support

### PR DESCRIPTION
**Pull request by ricardopereira**

### CODE REVIEW

**Comment by ricardopereira** [comment]
@rvi What do you think?

I tested it using a Cartfile like:

```
github "whitesmith/msgpack-objective-C" "carthage-support"
```

and it's working.

**Comment by rvi** [comment]
Hi, Ricardo,

Thanks for this PR, I didn't saw the notification 6 days ago.

**Comment by ricardopereira** [comment]
@rvi Thanks. Could you generate a new pod version please?

**Comment by rvi** [comment]
Why, you can't use carthage if I don't regenerate a new pod version?

**Comment by ricardopereira** [comment]
@rvi I enabled `ENABLE_MODULES` so the way you import the code is different:

`#import "MessagePack.h"` (non-modular import directives) should now use modular import directives like `#import <msgpack/msgpack.h>`. I added the umbrella header `msgpack.h` so if you have a framework with `msgpack-objective-C` dependency (that's my case BTW 😄) and you want to support Carthage and CocoaPods, then you will use `#import <msgpack/msgpack.h>` but it will currently fail using pods because the `msgpack.h` doesn't exist. At least, I think that's what's happening right now when I'm trying to use my framework with CocoaPods:

**Comment by ricardopereira** [comment]
But let me try something different. I will turn off `ENABLE_MODULES` and see if everything works without a new pod version.

**Comment by ricardopereira** [comment]
It works. All good 😁 Thanks

Just one note. I can only use it with Carthage by specifying the branch: `github "rvi/msgpack-objective-C" "master"`. But, we need a `tag` (i.e. `0.1.9`) with these changes to be able to use it like `github "rvi/msgpack-objective-C"`.

**Pull request merged**
