### PR TITLE
Revert "Update project settings"

### PR DESCRIPTION
**Pull request by funkyboy**
This reverts commit e9f7b144b9a06deee15fc55d36e8b7be6b919509.

So that I can use Xcode 8.3 and Cocoapods 0.37.2 to update the pod. This lints correctly.

```
msgpack-objective-C> pod lib lint
 -> msgpack (0.2.0)

msgpack passed validation.
msgpack-objective-C>
```

### CODE REVIEW

**Comment by funkyboy** [comment]
@rvi ready for your review. As soon as you merge into master I'll push the new pod to trunk. Ok?

**Comment by rvi** [comment]
Sure, go for it! 🚀

**Comment by funkyboy** [comment]
Oops I forgot.
After merging you are gonna need to:

```
git pull
git tag '0.2.0'
git push --tags
```

**Comment by funkyboy** [comment]
@rvi See above :)

**Comment by rvi** [comment]
@funkyboy Done. You might have to delete your local tag 0.2.0 (created 2 days ago) when I tried to submit your changes. I just deleted it and recreated because was never submitted to trunk.

**Comment by funkyboy** [comment]
@rvi I fetched changes from my trunk. Don't know if the tag was lost there. Thanks anyway.
Now shivering about this:
```
msgpack-objective-C> pod trunk push msgpack.podspec 
Updating spec repo `master`
[!] The `master` repo requires CocoaPods 1.0.0 -  (currently using 0.37.2)
Update CocoaPods, or checkout the appropriate tag in the repo.
msgpack-objective-C>
```

**Comment by funkyboy** [comment]
@rvi @ricardopereira and of course when I update to `1.0.0` it doesn't find the ☔️ 
😠 

```
msgpack-objective-C> pod lib lint

 -> msgpack (0.2.0)
    - ERROR | [iOS] xcodebuild: Returned an unsuccessful exit code. You can use `--verbose` for more information.
    - ERROR | xcodebuild:  /Users/cesare/Library/Developer/Xcode/DerivedData/App-apwmvkwggxjmvvbfofrypeiwdyfe/Build/Products/Release-iphonesimulator/msgpack/msgpack.framework/Modules/module.modulemap:3:19: error: umbrella header 'msgpack-umbrella2.h' not found
    - NOTE  | xcodebuild:  /var/folders/r3/yyh_7qtd7rzb7fdpdtvkcxmh0000gn/T/CocoaPods/Lint/App/main.m:3:9: fatal error: could not build module 'msgpack'

[!] msgpack did not pass validation, due to 2 errors.
You can use the `--no-clean` option to inspect any issue.
msgpack-objective-C> 
```

This is 🍌 🍌 🍌 🍌

**Comment by rvi** [comment]
Oh man

**Comment by rvi** [comment]
Maybe it's time to submit a cocoapods issue? Or try to do the pod from scratch...

I remember I had to create a custom modulemap, otherwise, it wouldn't compile, mainly because of the C code embedded.

**Pull request merged**
